### PR TITLE
migrate to viewer 5.0

### PR DESCRIPTION
**Pull request by xiaodongliang**
and also some tunes to make the sample easier understand

### CODE REVIEW

**Comment by augustogoncalves** [comment]
This reference still there, but returns 404, right?

`<script language="JavaScript" src="https://developer.api.autodesk.com/modelderivative/v2/viewers/three.min.js"></script>`

**Comment by xiaodongliang** [comment]
@augustogoncalves yes, 404, but it does not affect model loading. Can I simply remove it?

**Comment by augustogoncalves** [comment]
yes, please do, thanks.

**Comment by xiaodongliang** [comment]
done. please check and merge. thanks!

**Pull request merged**
